### ISSUE TITLE
** Online Manual ** here in Wiki

### ISSUE THREAD

**Issue by ErikS-web** [kamilsss655/ESPRI#15]
[<img align="right"  width="110" 
src="https://github.com/kamilsss655/ESPRI/assets/148579604/4671903e-d92d-4d54-a6be-ac5040c4d494">](https://github.com/kamilsss655/ESPRI/wiki)
<br>
The **manual** for this ESPRI project is **Online available** in the [Wiki](https://github.com/kamilsss655/ESPRI/wiki).
<br>
You can also select [<img width="75" src="https://github.com/kamilsss655/ESPRI/assets/148579604/ff2525ff-9f43-4664-bc4e-1103ec507dbd" >](https://github.com/kamilsss655/ESPRI/wiki) at the top
<br>
If you have an idea for the manual, [create an Issue with label [Documentation]](https://github.com/kamilsss655/ESPRI/issues/new)

**Comment by chinesejacklee** [comment]
Hi there, my first comment, great work! how do I set the esp32 so it can be connected with my local WIFI pls? I can't find anything in the user manual talks about it. I tried to change the wifi to the 'station mode', but I am now stuck and can not connect with the the http://192.168.4.1 anymore. Can anyone help pls?
