### ISSUE TITLE
[Release Notes] Tip: Point to the Wiki for Flash instructions

### ISSUE THREAD

**Issue by ErikS-web** [kamilsss655/ESPRI#19]
In release note you wite :

o To flash run esptool.py `write_flash 0x0 espri.bin`

Suggest to add there :

o Read the Online Manual (Wiki) for instructions [`here`](https://github.com/kamilsss655/ESPRI/wiki/40-%E2%80%90--How2-program-ESP#how2-program-the-esp)

**Comment by kamilsss655** [comment]
Done
