### ISSUE TITLE
[Hardware - PCB] Orientation of  ALL 100uF Tantalum Chip Capacitors should be rotated

### ISSUE THREAD

**Issue by ErikS-web** [kamilsss655/ESPRI#23]
**Reference :** (Google search for "_tantalum elco polarisation_"..)

![The stripe Bar marking on the Solid Tantalum Chip Capacitors](https://github.com/kamilsss655/ESPRI/assets/148579604/3926a4a3-e7e3-4a63-81bf-a48f1244e560)

**Added polarisation in Schematic :**

![Corrected Schematic](https://github.com/kamilsss655/ESPRI/assets/148579604/fb99b260-ba2f-42b7-803b-491540bcb616)

**Resulting in :** _ALL 100uF capacitors should be rotated._

![Corrected PCB](https://github.com/kamilsss655/ESPRI/assets/148579604/ca4b42f6-7beb-4406-b676-e40166769431)

**Comment by kamilsss655** [comment]
This is correct. Updating README.

Corrected in V2 board.

Well done @ErikS-web !

**Comment by ErikS-web** [comment]
- Updated .CPL file into file rotated-Fixed-C1-C6-J1EXT-cpl.csv
- Wiki update with the info of this Issue #23
- New orders should be ok and info on how2  modify _already delivered boards_ is clear.

**Comment by kamilsss655** [comment]
Nice @ErikS-web !

Is there any additional action to be taken in this issue? If not, then I guess it can be closed?

**Comment by ErikS-web** [comment]
Yeah I will close this one ;-)
