### ISSUE TITLE
[FEATURE] A TX-start-delay and a tiny Tail-delay might be usefull

### ISSUE THREAD

**Issue by ErikS-web** [kamilsss655/ESPRI#25]
Tested with V8.0

![afbeelding](https://github.com/kamilsss655/ESPRI/assets/148579604/d62c5121-aef5-4373-bf16-b71300207a44)

[WAV beacon in Release v0.8.0.zip](https://github.com/kamilsss655/ESPRI/files/15077275/WAV.beacon.in.Release.v0.8.0.zip)

**Comment by ErikS-web** [comment]
Yes this is OK

![OK](https://github.com/kamilsss655/ESPRI/assets/148579604/06d57da2-475f-4dbe-9761-91a6176bdac5)

[ok.zip](https://github.com/kamilsss655/ESPRI/files/15099074/ok.zip)

**Comment by kamilsss655** [comment]
Cool! Here is spectrogram recorded vs original:
![spectrogram](https://github.com/kamilsss655/ESPRI/assets/8842065/3c74455b-0837-44ce-a8a6-4479b8e23bdf)

Although it is likely distorted due to mp3 compression of the recording.
