### ISSUE TITLE
can not set local wifi with the esp32

### ISSUE THREAD

**Issue by chinesejacklee** [kamilsss655/ESPRI#43]
Hi there, my first comment, great work! how do I set the esp32 so it can be connected with my local WIFI pls? I can't find anything in the user manual talks about it. I tried to change the wifi to the 'station mode', but I am now stuck and can not connect with the the http://192.168.4.1/ anymore. Can anyone help pls?

**Comment by ErikS-web** [comment]
Did you had a look at the logging... via `Console` that is available in  [`🗲ESP-launchpad🗲`](https://espressif.github.io/esp-launchpad/)

There you can see under what `(new) ip-adress` the ESP is connected in `your home-network`
Look for GREEN LINE with **esp_netif_handlers: sta ip:** 


You can also have a look in your router-modem.

p.s. You can always reprogram the ESP, and try again

**Comment by kamilsss655** [comment]
Thanks Erik!
