### ISSUE TITLE
[FEATURE] https://www.tindie.com/

### ISSUE THREAD

**Issue by xi-9** [kamilsss655/ESPRI#64]
You are planing  make a real working hardware with powier?
For example with 18650 or AA (or step up from 1V to 5V : USB )
battery is heavy meybe making a simple socket for k1 to USB cable ? Or cable without usb?

Many programmers cant use soldering ;D

**Comment by kamilsss655** [comment]
Me no plan make real hardware with powier. Battery heavy. Air is free, but maybe simple make someting.
